"""
app/models/testcase.py

SQLAlchemy ORM model for the TestCase entity.

A TestCase is the central entity of the platform. It is created by the AI
generation pipeline and progresses through a status lifecycle until it is
synced to Zephyr and executed via Harness.

Lifecycle:
    AI Generation → DRAFT → PENDING → APPROVED → (Zephyr Synced) → Execution
                                     ↘ REJECTED
"""

from sqlalchemy import Column, String, Text, Enum as SAEnum, DateTime, ForeignKey, ARRAY
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
# from app.core.database import Base
# from app.core.constants import TestCaseStatus, TestCaseType, SyncStatus


class TestCase:  # (Base):
    """
    Represents a generated test case entity.

    Columns:
        id              : UUID primary key
        title           : Short descriptive title of the test case
        description     : Full description of what the test covers
        type            : TestCaseType (UI | API | Regression)
        status          : TestCaseStatus lifecycle state
        bdd_content     : Gherkin feature file content (generated by BDD agent)
        selenium_code   : Java Selenium/TestNG automation code (generated by Selenium agent)
        tags            : Array of searchable tags (e.g. ["smoke", "auth"])
        zephyr_id       : Zephyr Scale test case ID (populated after sync)
        sync_status     : Zephyr sync lifecycle state
        created_by_id   : FK → User who triggered generation
        prompt_id       : FK → Prompt that led to this test case
        created_at      : Timestamp
        updated_at      : Timestamp (auto-updated on save)

    Relationships:
        created_by_user : User who owns this test case
        executions      : Execution records that include this test case
    """

    __tablename__ = "test_cases"

    # Columns – placeholder (uncomment when Base is wired)
    # id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    # title = Column(String(512), nullable=False)
    # description = Column(Text, nullable=True)
    # type = Column(SAEnum(TestCaseType), nullable=False)
    # status = Column(SAEnum(TestCaseStatus), default=TestCaseStatus.DRAFT)
    # bdd_content = Column(Text, nullable=True)
    # selenium_code = Column(Text, nullable=True)
    # tags = Column(ARRAY(String), default=list)
    # zephyr_id = Column(String(128), nullable=True)
    # sync_status = Column(SAEnum(SyncStatus), default=SyncStatus.NOT_SYNCED)
    # created_by_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    # created_at = Column(DateTime(timezone=True), server_default=func.now())
    # updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    def __repr__(self) -> str:
        pass
